"""Print a portfolio/P&L example generated by the Set 5 accounting engine."""

from datetime import datetime

from quant_system.backtest import FillEvent, OrderSide
from quant_system.portfolio import Portfolio


def main() -> int:
    timestamp = datetime(2026, 1, 5, 16)
    portfolio = Portfolio(100_000.0, allow_short_selling=True)
    fills = (
        FillEvent("a-buy", timestamp, "AAPL", OrderSide.BUY, 100, 100.0, 5.0, 0.0),
        FillEvent("a-sell", timestamp, "AAPL", OrderSide.SELL, 40, 115.0, 5.0, 0.0),
        FillEvent("m-sell", timestamp, "MSFT", OrderSide.SELL, 50, 200.0, 5.0, 0.0),
    )
    for fill in fills:
        portfolio.process_fill(fill)
    portfolio.update_market_price("AAPL", 110.0)
    portfolio.update_market_price("MSFT", 190.0)
    portfolio.record_snapshot(timestamp)

    print("PORTFOLIO")
    print(f"Cash                 {portfolio.cash:,.2f}")
    print(f"Equity               {portfolio.equity:,.2f}")
    print(f"Gross Realized P&L     {portfolio.gross_realized_pnl:,.2f}")
    print(f"Unrealized P&L         {portfolio.unrealized_pnl:,.2f}")
    print(f"Commission                {portfolio.total_commission:,.2f}")
    print("\nEXPOSURE")
    print(f"Gross Exposure        {portfolio.gross_exposure:,.2f}")
    print(f"Net Exposure          {portfolio.net_exposure:,.2f}")
    print(f"Gross Exposure %         {portfolio.gross_exposure_pct:.2%}")
    print(f"Net Exposure %           {portfolio.net_exposure_pct:.2%}")
    print("\nPOSITIONS")
    for symbol, position in portfolio.positions.items():
        print(f"{symbol:<6} {position.quantity:+5d}    Avg {position.average_price:,.2f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

